#!/usr/bin/env bash
# One-click dotfiles installer
#
#   curl -sSf https://raw.githubusercontent.com/silenaker/dotfiles/main/bootstrap.sh | bash
#
# Works on any Linux distribution (including WSL).  Idempotent.
#
# Generated by build.sh — do not edit directly.

set -euo pipefail

REPO_URL="${DOTFILES_REPO_URL:-https://github.com/silenaker/dotfiles.git}"

# ------------------------------------------------------------------
# Output helpers
# ------------------------------------------------------------------
green() { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
blue() { printf '\033[0;34m%s\033[0m\n' "$*"; }
dim() { printf '\033[2m%s\033[0m\n' "$*"; }

# merge_gitconfig <src>
#
# ── Algorithm ──
#
#   1. Parse <src> (a .gitconfig file) using git config --file --list.
#      This outputs flat "section.key=value" lines, one per key.
#      Git's own INI parser handles sections, subsections, quoting,
#      line-continuation, includes — no text-mode regex hacking.
#
#   2. For each key=value pair from the repo file:
#      a) Strip \r and trim whitespace (defence against CRLF / odd formatting).
#      b) Query the user's global config: git config --global --get <key>
#      c) Three-way decision:
#           - Key NOT set globally  →  git config --global <key> <value>  (add)
#           - Key set, same value   →  skip (already present)
#           - Key set, DIFF value   →  skip, report conflict (user wins)
#
# Requires: green(), dim(), yellow() helpers; git on PATH.
# Returns: 0 on success, 1 if <src> is missing.
merge_gitconfig() {
	local src="$1"
	local added=0 skipped=0 conflicts=0
	local key value existing

	if [ ! -f "$src" ]; then
		echo "  ERROR: source file not found: $src" >&2
		return 1
	fi

	# ── git config --file --list: git's own parser ──
	# Produces lines like "core.autocrlf=input" — no section headers,
	# no indentation, just canonical key=value pairs.
	while IFS='=' read -r key value || [ -n "$key" ]; do
		[ -z "$key" ] && continue

		# Defensive: strip CR and trim surrounding whitespace.
		# git config output is normally clean, but CRLF checkouts or
		# unusual config values could introduce artifacts.
		key="${key%$'\r'}"
		key="${key#"${key%%[![:space:]]*}"}"
		key="${key%"${key##*[![:space:]]}"}"
		value="${value%$'\r'}"
		value="${value#"${value%%[![:space:]]*}"}"
		value="${value%"${value##*[![:space:]]}"}"

		# Query the user's current global setting for this key
		existing="$(git config --global --get "$key" 2>/dev/null || true)"

		# ── Three-way merge decision ──
		if [ -z "$existing" ]; then
			# Key not set → safe to add the repo default
			git config --global "$key" "$value"
			green "  + ${key} = ${value}"
			added=$((added + 1))
		elif [ "$existing" = "$value" ]; then
			# Already set to the same value → nothing to do
			dim "  = ${key} = ${value}"
			skipped=$((skipped + 1))
		else
			# Set to a different value → user wins, report conflict
			yellow "  ~ ${key} = ${value}  (you have: ${existing} — kept yours)"
			conflicts=$((conflicts + 1))
		fi
	done < <(git config --file "$src" --list 2>/dev/null || true)

	if [ "$added" -eq 0 ] && [ "$conflicts" -eq 0 ]; then
		green "  (all keys already present)"
	elif [ "$added" -gt 0 ] || [ "$conflicts" -gt 0 ]; then
		green "  ${added} key(s) added, ${skipped} already present, ${conflicts} conflict(s) kept as-is"
	fi
	return 0
}

# merge_gitignore <src> <dst>
#
# ── Algorithm ──
#
#   for each line in <src>:
#       strip trailing \r                    # CRLF defence
#       skip if empty or starts with #       # blank / comment lines are not patterns
#       if line appears as an exact whole line in <dst>:
#           skip (report "=")                # already present, nothing to do
#       else:
#           append line to <dst>             # missing pattern, add it
#           report "+"
#
#   If <dst> does not exist at all, it is created as a copy of <src>
#   (first-install path: no merging needed).
#
# Requires: green(), dim() helpers (for output).
# Returns: 0 on success, 1 if <src> is missing.
merge_gitignore() {
	local src="$1" dst="$2"
	local added=0 skipped=0 line

	if [ ! -f "$src" ]; then
		echo "  ERROR: source file not found: $src" >&2
		return 1
	fi

	# ── First-install path: dst does not exist ──
	if [ ! -f "$dst" ]; then
		cp "$src" "$dst"
		while IFS= read -r line || [ -n "$line" ]; do
			line="${line%$'\r'}"
			[[ -z "$line" || "$line" == \#* ]] && continue
			green "  + ${line}"
			added=$((added + 1))
		done <"$src"
		green "  ${added} pattern(s) added"
		return 0
	fi

	# ── Merge path: dst exists, compare line by line ──
	while IFS= read -r line || [ -n "$line" ]; do
		line="${line%$'\r'}"
		[[ -z "$line" || "$line" == \#* ]] && continue
		# grep -qxF: exact whole-line, fixed-string (see design note #1)
		if grep -qxF "$line" "$dst" 2>/dev/null; then
			dim "  = ${line}"
			skipped=$((skipped + 1))
		else
			echo "$line" >>"$dst"
			green "  + ${line}"
			added=$((added + 1))
		fi
	done <"$src"

	if [ "$added" -eq 0 ]; then
		green "  (all patterns already present)"
	else
		green "  ${added} pattern(s) added, ${skipped} already present"
	fi
	return 0
}

# ------------------------------------------------------------------
# Preflight
# ------------------------------------------------------------------
if ! command -v git &>/dev/null; then
	echo "  ERROR: git is required but not found. Install git first, then re-run."
	exit 1
fi

# ------------------------------------------------------------------
# Clone repo into a temporary directory
# ------------------------------------------------------------------
# -c core.autocrlf=false: force LF line endings so CRLF doesn't
#   interfere with line-by-line merge logic.
# trap EXIT: the temp directory is always cleaned up, even on error.
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo ""
echo "  silenaker/dotfiles — one-click installer"
echo "  ========================================="
echo ""

echo "→ Cloning dotfiles (shallow)..."
if ! git -c core.autocrlf=false clone --depth 1 "$REPO_URL" "$TMPDIR" 2>/dev/null; then
	echo "  ERROR: failed to clone $REPO_URL"
	exit 1
fi
echo ""

# ------------------------------------------------------------------
# .gitconfig  —  key-by-key merge via git config (see lib/merge-gitconfig.sh)
# ------------------------------------------------------------------
blue "◆ .gitconfig"
merge_gitconfig "$TMPDIR/.gitconfig"
echo ""

# ------------------------------------------------------------------
# .gitignore_global  —  line-by-line merge (see lib/merge-gitignore.sh)
# ------------------------------------------------------------------
blue "◆ .gitignore_global"
gitignore_target="$(git config --get core.excludesFile)"
if [ -z "$gitignore_target" ]; then
	gitignore_target="$HOME/.gitignore_global"
else
	# Expand ~/ prefix if present (git config may return paths like ~/.gitignore)
	gitignore_target="${gitignore_target/#\~/$HOME}"
fi
merge_gitignore "$TMPDIR/.gitignore_global" "$gitignore_target"
echo ""

# ------------------------------------------------------------------
# Done
# ------------------------------------------------------------------
green "◆ Done."
echo ""
echo "  Legend:  + added   = already present   ~ conflict (your value kept)"
echo ""
