#!/usr/bin/env bash
# One-click dotfiles installer
#
#   curl -sSf https://raw.githubusercontent.com/silenaker/dotfiles/main/bootstrap.sh | bash
#
# Works on any Linux distribution (including WSL).  Idempotent.
#
# Generated by build.sh — do not edit directly.

set -euo pipefail

REPO_URL="${DOTFILES_REPO_URL:-https://github.com/silenaker/dotfiles.git}"

# ------------------------------------------------------------------
# Output helpers
# ------------------------------------------------------------------
green() { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
blue() { printf '\033[0;34m%s\033[0m\n' "$*"; }
dim() { printf '\033[2m%s\033[0m\n' "$*"; }

# merge_gitconfig <src>
#
# ── Algorithm ──
#
#   1. Parse <src> (a .gitconfig file) using git config --file --list.
#      This outputs flat "section.key=value" lines, one per key.
#      Git's own INI parser handles sections, subsections, quoting,
#      line-continuation, includes — no text-mode regex hacking.
#
#   2. For each key=value pair from the repo file:
#      a) Strip \r and trim whitespace (defence against CRLF / odd formatting).
#      b) Query the user's global config: git config --global --get <key>
#      c) Three-way decision:
#           - Key NOT set globally  →  git config --global <key> <value>  (add)
#           - Key set, same value   →  skip (already present)
#           - Key set, DIFF value   →  skip, report conflict (user wins)
#
# Requires: green(), dim(), yellow() helpers; git on PATH.
# Returns: 0 on success, 1 if <src> is missing.
merge_gitconfig() {
	local src="$1"
	local added=0 skipped=0 conflicts=0
	local key value existing

	if [ ! -f "$src" ]; then
		echo "  ERROR: source file not found: $src" >&2
		return 1
	fi

	# ── git config --file --list: git's own parser ──
	# Produces lines like "core.autocrlf=input" — no section headers,
	# no indentation, just canonical key=value pairs.
	while IFS='=' read -r key value || [ -n "$key" ]; do
		[ -z "$key" ] && continue

		# Defensive: strip CR and trim surrounding whitespace.
		# git config output is normally clean, but CRLF checkouts or
		# unusual config values could introduce artifacts.
		key="${key%$'\r'}"
		key="${key#"${key%%[![:space:]]*}"}"
		key="${key%"${key##*[![:space:]]}"}"
		value="${value%$'\r'}"
		value="${value#"${value%%[![:space:]]*}"}"
		value="${value%"${value##*[![:space:]]}"}"

		# Query the user's current global setting for this key
		existing="$(git config --global --get "$key" 2>/dev/null || true)"

		# ── Three-way merge decision ──
		if [ -z "$existing" ]; then
			# Key not set → safe to add the repo default
			git config --global "$key" "$value"
			green "  + ${key} = ${value}"
			added=$((added + 1))
		elif [ "$existing" = "$value" ]; then
			# Already set to the same value → nothing to do
			dim "  = ${key} = ${value}"
			skipped=$((skipped + 1))
		else
			# Set to a different value → user wins, report conflict
			yellow "  ~ ${key} = ${value}  (you have: ${existing} — kept yours)"
			conflicts=$((conflicts + 1))
		fi
	done < <(git config --file "$src" --list 2>/dev/null || true)

	if [ "$added" -eq 0 ] && [ "$conflicts" -eq 0 ]; then
		green "  (all keys already present)"
	elif [ "$added" -gt 0 ] || [ "$conflicts" -gt 0 ]; then
		green "  ${added} key(s) added, ${skipped} already present, ${conflicts} conflict(s) kept as-is"
	fi
	return 0
}

# merge_gitignore <src> <dst>
#
# ── Algorithm ──
#
#   for each line in <src>:
#       strip trailing \r                    # CRLF defence
#       skip if empty or starts with #       # blank / comment lines are not patterns
#       if line appears as an exact whole line in <dst>:
#           skip (report "=")                # already present, nothing to do
#       else:
#           append line to <dst>             # missing pattern, add it
#           report "+"
#
#   If <dst> does not exist at all, it is created as a copy of <src>
#   (first-install path: no merging needed).
#
# Requires: green(), dim() helpers (for output).
# Returns: 0 on success, 1 if <src> is missing.
merge_gitignore() {
	local src="$1" dst="$2"
	local added=0 skipped=0 line

	if [ ! -f "$src" ]; then
		echo "  ERROR: source file not found: $src" >&2
		return 1
	fi

	# ── First-install path: dst does not exist ──
	if [ ! -f "$dst" ]; then
		cp "$src" "$dst"
		while IFS= read -r line || [ -n "$line" ]; do
			line="${line%$'\r'}"
			[[ -z "$line" || "$line" == \#* ]] && continue
			green "  + ${line}"
			added=$((added + 1))
		done <"$src"
		green "  ${added} pattern(s) added"
		return 0
	fi

	# ── Merge path: dst exists, compare line by line ──
	while IFS= read -r line || [ -n "$line" ]; do
		line="${line%$'\r'}"
		[[ -z "$line" || "$line" == \#* ]] && continue
		# grep -qxF: exact whole-line, fixed-string (see design note #1)
		if grep -qxF "$line" "$dst" 2>/dev/null; then
			dim "  = ${line}"
			skipped=$((skipped + 1))
		else
			echo "$line" >>"$dst"
			green "  + ${line}"
			added=$((added + 1))
		fi
	done <"$src"

	if [ "$added" -eq 0 ]; then
		green "  (all patterns already present)"
	else
		green "  ${added} pattern(s) added, ${skipped} already present"
	fi
	return 0
}

# merge_bashrc <src> <dst>
#
# ── Algorithm ──
#
#   Managed-block merge with sentinel markers:
#
#       # >>> dotfiles .bashrc >>>
#       ... managed content from repo ...
#       # <<< dotfiles .bashrc <<<
#
#   1. If <dst> does not exist:
#        Copy <src> to <dst> as-is (first-install path).
#
#   2. If <dst> exists and contains the markers:
#        Replace everything between (and including) the markers
#        with the current <src> content wrapped in fresh markers.
#        If the new content matches what is already between the
#        markers, skip — nothing to do.
#
#   3. If <dst> exists but does NOT contain the markers:
#        Append the <src> content wrapped in markers.
#        An extra blank line is inserted before the block so
#        the user's existing content and the managed block are
#        visually separated.
#
#   This strategy is safe: user customisation above or below the
#   managed block is never touched.  The user can freely add
#   aliases, exports, or source commands outside the markers.
#
# Requires: green(), dim() helpers; sed, grep, head, tail on PATH.
# Returns: 0 on success, 1 if <src> is missing.
merge_bashrc() {
	local src="$1" dst="$2"
	local start_marker="# >>> dotfiles .bashrc >>>"
	local end_marker="# <<< dotfiles .bashrc <<<"

	if [ ! -f "$src" ]; then
		echo "  ERROR: source file not found: $src" >&2
		return 1
	fi

	# ── Normalise src content (strip CR) ──
	local src_content
	src_content="$(sed 's/\r$//' "$src")"

	# ── First-install path: dst does not exist ──
	# Wrap content in sentinel markers so subsequent runs recognise the
	# managed block and enter the replace path (not the append path).
	if [ ! -f "$dst" ]; then
		{
			printf '%s\n' "$start_marker"
			printf '%s\n' "$src_content"
			printf '%s\n' "$end_marker"
		} >"$dst"
		green "  + .bashrc (created)"
		local added=0 line
		while IFS= read -r line || [ -n "$line" ]; do
			line="${line%$'\r'}"
			[[ -z "$line" || "$line" == \#* ]] && continue
			added=$((added + 1))
		done <<<"$src_content"
		green "  ${added} active line(s) installed"
		return 0
	fi

	# ── dst has markers: replace the managed block ──
	# Normalise line endings for reliable marker detection — CRLF
	# (from Windows editors) would otherwise defeat grep -xF.
	# Use a here-string (<<<) rather than process substitution
	# because /dev/fd redirection is unreliable on some platforms (WSL).
	local dst_norm
	dst_norm="$(sed 's/\r$//' "$dst")"
	if grep -qxF "$start_marker" <<<"$dst_norm" 2>/dev/null &&
		grep -qxF "$end_marker" <<<"$dst_norm" 2>/dev/null; then
		local start_ln end_ln
		start_ln="$(grep -nxF "$start_marker" <<<"$dst_norm" | head -1 | cut -d: -f1)"
		end_ln="$(grep -nxF "$end_marker" <<<"$dst_norm" | head -1 | cut -d: -f1)"

		if [ -n "$start_ln" ] && [ -n "$end_ln" ] && [ "$start_ln" -lt "$end_ln" ]; then
			# Extract current block content (between markers, exclusive).
			# Strip CR so comparison works when dst has CRLF endings.
			local old_content
			old_content="$(sed -n "$((start_ln + 1)),$((end_ln - 1))p" "$dst" | sed 's/\r$//')"

			if [ "$old_content" = "$src_content" ]; then
				green "  (up to date)"
				return 0
			fi

			# Replace: lines before start + new block + lines after end.
			# Normalise CRLF from preserved user sections for consistent
			# LF-only output (prevents mixed line endings).
			{
				head -n $((start_ln - 1)) "$dst" | sed 's/\r$//'
				printf '%s\n' "$start_marker"
				printf '%s\n' "$src_content"
				printf '%s\n' "$end_marker"
				tail -n +$((end_ln + 1)) "$dst" | sed 's/\r$//'
			} >"${dst}.tmp"
			mv "${dst}.tmp" "$dst"
			green "  + .bashrc block updated"
			return 0
		fi
	fi

	# ── dst exists, no (valid) markers: append managed block ──
	{
		cat "$dst"
		printf '\n%s\n' "$start_marker"
		printf '%s\n' "$src_content"
		printf '%s\n' "$end_marker"
	} >"${dst}.tmp"
	mv "${dst}.tmp" "$dst"
	green "  + .bashrc block appended"
	return 0
}

# ------------------------------------------------------------------
# Preflight
# ------------------------------------------------------------------
if ! command -v git &>/dev/null; then
	echo "  ERROR: git is required but not found. Install git first, then re-run."
	exit 1
fi

# ------------------------------------------------------------------
# Clone repo into a temporary directory
# ------------------------------------------------------------------
# -c core.autocrlf=false: force LF line endings so CRLF doesn't
#   interfere with line-by-line merge logic.
# trap EXIT: the temp directory is always cleaned up, even on error.
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo ""
echo "  silenaker/dotfiles — one-click installer"
echo "  ========================================="
echo ""

echo "→ Cloning dotfiles (shallow)..."
if ! git -c core.autocrlf=false clone --depth 1 "$REPO_URL" "$TMPDIR" 2>/dev/null; then
	echo "  ERROR: failed to clone $REPO_URL"
	exit 1
fi
echo ""

# ------------------------------------------------------------------
# .gitconfig  —  key-by-key merge via git config (see lib/merge-gitconfig.sh)
# ------------------------------------------------------------------
blue "◆ .gitconfig"
merge_gitconfig "$TMPDIR/.gitconfig"
echo ""

# ------------------------------------------------------------------
# .gitignore_global  —  line-by-line merge (see lib/merge-gitignore.sh)
# ------------------------------------------------------------------
blue "◆ .gitignore_global"
gitignore_target="$(git config --get core.excludesFile)"
if [ -z "$gitignore_target" ]; then
	gitignore_target="$HOME/.gitignore_global"
else
	# Expand ~/ prefix if present (git config may return paths like ~/.gitignore)
	gitignore_target="${gitignore_target/#\~/$HOME}"
fi
merge_gitignore "$TMPDIR/.gitignore_global" "$gitignore_target"
echo ""

# ------------------------------------------------------------------
# .bashrc  —  managed-block merge (see lib/merge-bashrc.sh)
# ------------------------------------------------------------------
blue "◆ .bashrc"
if [ -f "$TMPDIR/.bashrc" ]; then
	merge_bashrc "$TMPDIR/.bashrc" "$HOME/.bashrc"
else
	dim "  (no .bashrc in repo — skipping)"
fi
echo ""

# ------------------------------------------------------------------
# Done
# ------------------------------------------------------------------
green "◆ Done."
echo ""
echo "  Legend:  + added   = already present   ~ conflict (your value kept)"
echo ""
