#!/usr/bin/env bash
# build.sh — assemble bootstrap.sh from lib/ modules
#
# ── Purpose ──
#
#   bootstrap.sh is a single-file curl-pipe-bash installer.  For
#   development we keep the merge logic in separate, testable modules
#   under lib/.  This script assembles them into the deliverable.
#
# ── Assembly order ──
#
#   1. Header: shebang, description, config, output helpers
#   2. Lib modules (merge logic one per dotfile)
#   3. Main orchestration:
#        • Preflight (dependency checking)
#        • Clone repo to temp dir (shallow, force LF)
#        • Call each merge function
#        • Done summary
#
#   Order matters: helpers must be defined before modules,
#   modules before the orchestration that calls them.
#
# ── Why not just source? ──
#
#   bootstrap.sh is delivered via curl | bash.  It must be a single,
#   self-contained file.  The build step inlines everything.
#
# ── Extending ──
#
#   To add a new dotfile:
#   1. Create lib/merge-<name>.sh with a merge_<name>() function.
#   2. Add an emit_file line below.
#   3. Add a call in the MAIN orchestration block.
#   4. Write unit tests in test/test-merge-<name>.sh
#   5. Add integration assertions in test/test-bootstrap.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$ROOT/bootstrap.sh"

# ------------------------------------------------------------------
# Helper: emit a file into the output
# ------------------------------------------------------------------
# Strips the shebang line and trailing blank lines from module files
# so they inline cleanly.  Module files are valid standalone scripts
# (for sourcing in tests) but here we only want the function body.
emit_file() {
	local label="$1" path="$2"
	echo "" >>"$OUT"
	sed -e '/^#!/d' -e '${/^$/d;}' "$path" >>"$OUT"
}

# ==================================================================
# 1. Header: shebang, description, config
# ==================================================================
cat >"$OUT" <<'HEADER'
#!/usr/bin/env bash
# One-click dotfiles installer
#
#   curl -sSf https://raw.githubusercontent.com/silenaker/dotfiles/main/bootstrap.sh | bash
#
# Works on any Linux distribution (including WSL).  Idempotent.
#
# Generated by build.sh — do not edit directly.

set -euo pipefail

REPO_URL="${DOTFILES_REPO_URL:-https://github.com/silenaker/dotfiles.git}"

# ------------------------------------------------------------------
# Output helpers
# ------------------------------------------------------------------
green() { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
blue() { printf '\033[0;34m%s\033[0m\n' "$*"; }
dim() { printf '\033[2m%s\033[0m\n' "$*"; }
HEADER

# ==================================================================
# 2. Lib modules (merge logic)
# ==================================================================
emit_file "merge-gitconfig" "$ROOT/lib/merge-gitconfig.sh"
emit_file "merge-gitignore" "$ROOT/lib/merge-gitignore.sh"
emit_file "merge-bashrc" "$ROOT/lib/merge-bashrc.sh"

# ==================================================================
# 3. Main orchestration
# ==================================================================
cat >>"$OUT" <<'MAIN'

# ------------------------------------------------------------------
# Preflight
# ------------------------------------------------------------------
if ! command -v git &>/dev/null; then
	echo "  ERROR: git is required but not found. Install git first, then re-run."
	exit 1
fi

# ------------------------------------------------------------------
# Clone repo into a temporary directory
# ------------------------------------------------------------------
# -c core.autocrlf=false: force LF line endings so CRLF doesn't
#   interfere with line-by-line merge logic.
# trap EXIT: the temp directory is always cleaned up, even on error.
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo ""
echo "  silenaker/dotfiles — one-click installer"
echo "  ========================================="
echo ""

echo "→ Cloning dotfiles (shallow)..."
if ! git -c core.autocrlf=false clone --depth 1 "$REPO_URL" "$TMPDIR" 2>/dev/null; then
	echo "  ERROR: failed to clone $REPO_URL"
	exit 1
fi
echo ""

# ------------------------------------------------------------------
# .gitconfig  —  key-by-key merge via git config (see lib/merge-gitconfig.sh)
# ------------------------------------------------------------------
blue "◆ .gitconfig"
merge_gitconfig "$TMPDIR/.gitconfig"
echo ""

# ------------------------------------------------------------------
# .gitignore_global  —  line-by-line merge (see lib/merge-gitignore.sh)
# ------------------------------------------------------------------
blue "◆ .gitignore_global"
gitignore_target="$(git config --get core.excludesFile)"
if [ -z "$gitignore_target" ]; then
	gitignore_target="$HOME/.gitignore_global"
else
	# Expand ~/ prefix if present (git config may return paths like ~/.gitignore)
	gitignore_target="${gitignore_target/#\~/$HOME}"
fi
merge_gitignore "$TMPDIR/.gitignore_global" "$gitignore_target"
echo ""

# ------------------------------------------------------------------
# .bashrc  —  managed-block merge (see lib/merge-bashrc.sh)
# ------------------------------------------------------------------
blue "◆ .bashrc"
if [ -f "$TMPDIR/.bashrc" ]; then
	merge_bashrc "$TMPDIR/.bashrc" "$HOME/.bashrc"
else
	dim "  (no .bashrc in repo — skipping)"
fi
echo ""

# ------------------------------------------------------------------
# Done
# ------------------------------------------------------------------
green "◆ Done."
echo ""
echo "  Legend:  + added   = already present   ~ conflict (your value kept)"
echo ""
MAIN

# ==================================================================
# Finish
# ==================================================================
chmod +x "$OUT"
echo "  → $(basename "$OUT") assembled ($(wc -l <"$OUT") lines)"
